import { ContractionRule } from '~/type';

export const contractions: ContractionRule[] = [
  { from: 'i am', to: "I'm" },
  { from: 'is not', to: "isn't" },
  { from: 'are not', to: "aren't" },
  { from: 'was not', to: "wasn't" },
  { from: 'were not', to: "weren't" },
  { from: 'do not', to: "don't" },
  { from: 'does not', to: "doesn't" },
  { from: 'did not', to: "didn't" },
  { from: 'have not', to: "haven't" },
  { from: 'has not', to: "hasn't" },
  { from: 'had not', to: "hadn't" },
  { from: 'will not', to: "won't" },
  { from: 'would not', to: "wouldn't" },
  { from: 'i will', to: "I'll" },
  { from: 'we will', to: "we'll" },
  { from: 'he will', to: "he'll" },
  { from: 'she will', to: "she'll" },
  { from: 'it will', to: "it'll" },
  { from: 'they will', to: "they'll" },
  { from: 'he is', to: "he's" },
  { from: 'she is', to: "she's" },
  { from: 'it is', to: "it's" },
  { from: 'they are', to: "they're" },
  { from: 'you are', to: "you're" },
  { from: 'i have', to: "I've" },
  { from: 'i had', to: "I'd" },
  { from: 'you had', to: "you'd" },
  { from: 'he had', to: "he'd" },
  { from: 'she had', to: "she'd" },
  { from: 'he has', to: "he's" },
  { from: 'would have', to: "would've" },
  { from: 'might have', to: "might've" },
  { from: 'can not', to: "can't" },
  { from: 'would not', to: "wouldn't" },
  { from: 'we have', to: "we've" }
];
